### PR TITLE
Prefixing BrowseNode response struct with Amazon

### PR DESCRIPTION
**Pull request by metaprogrammed**
CC @artnez

### CODE REVIEW

**Comment by dominicphillips** [comment]
Thank you @metaprogrammed ! How about we define the "Ancestors" like this ?

```
BrowseNodes  *[]BrowseNode `xml:"Ancestors>BrowseNode"`
```

That way we'd still be able to index / range over it, e.g. 

```
(*result.AmazonItems.Items[0].BrowseNodes[0].BrowseNodes)[0]
```

**Comment by metaprogrammed** [comment]
The type change sounds good to me.

```
type AmazonBrowseNode struct {
    BrowseNodeId string              `xml:"BrowseNodeId"`
    Name         string              `xml:"Name"`
    Ancestors    *[]AmazonBrowseNode `xml:"Ancestors>BrowseNode"`
}
```

My only thoughts are that the `Ancestors` field on the `AmazonBrowseNode` should still contain some distinction in the name, because these BrowseNodes are specifically ones that are related to the BrowseNode that belongs to the `AmazonItem`, so maybe keep it named `Ancestors` or something like `AncestorBrowseNodes`?

**Comment by dominicphillips** [comment]
Hm, makes sense! Thank you @metaprogrammed for contributing!

**Comment by metaprogrammed** [comment]
Anytime! And thank you for this maintaining this awesome client!

**Pull request merged**
